version: '3.8'

services:
  
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=gb_ecommerce
    networks:
      - compose-bridge
  api:
    build: ./api_ecommerce
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api_ecommerce/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - compose-bridge
volumes:
  postgres_data:

networks:
  compose-bridge:
    driver: bridge