# Generated by Django 5.0.1 on 2024-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('products', models.ManyToManyField(blank=True, related_name='suppliers', to='products.productmodel')),
            ],
        ),
    ]
