# Generated by Django 5.0.1 on 2024-01-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliermodel',
            name='products',
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
