# Generated by Django 5.0.1 on 2024-01-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistorymodel',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
