# Generated by Django 5.0.1 on 2024-01-14 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_pricehistorymodel_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
