# Generated by Django 5.0.1 on 2024-01-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_reviewmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='internalCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
