# Generated by Django 5.0.1 on 2024-01-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_productmodel_internalcode_productmodel_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='categories',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.categorymodel'),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='server.productmodel'),
        ),
    ]
