name: Django CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 4
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python-version: [3.12.1]
    steps:
    
    - uses: actions/checkout@v3
    - name: Usando Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Instalando Depêndecias
      run: |
        python -m pip install --upgrade pip
        pip install -r api_ecommerce/requirements.txt
        
    - name: Iniciando Testes
      run: |
        python api_ecommerce/manage.py test api_ecommerce
